services:
    server:
        container_name: pms_server
        depends_on:
            - database
        logging:
            driver: "json-file"
            options:
                max-size: "5m" # Each log file has a maximum size of 5 MB
                max-file: "2" # Up to 2 rotated files are retained per container

    prisma_studio:
        restart: on-failure:2
        build:
            context: ./src/alt_schema
            dockerfile: Dockerfile
        container_name: prisma_studio
        depends_on:
            - database

    database:
        image: postgres:14.3
        container_name: pms_database
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
    app_node_modules:
