services:
    reverse_proxy:
        build:
            context: ./.nginx
            dockerfile: Dockerfile
        container_name: pms_reverse_proxy
        restart: unless-stopped
        ports:
            - 80:80
        depends_on:
            - server
        develop:
            watch:
                - path: .nginx/
                  target: /etc/nginx/conf.d
                  action: sync+restart
        logging:
            driver: "json-file"
            options:
                max-size: "5m" # Each log file has a maximum size of 5 MB
                max-file: "2" # Up to 2 rotated files are retained per container
