services:
    server:
        restart: on-failure:5
        env_file:
            - .env.dev
        ports:
            - 3002:3000
        command: ["run", "dev"]
        develop:
            watch:
                - path: ./
                  target: /app
                  action: sync
                  ignore:
                      - node_modules/
                      - ./.nginx
                - path: package.json
                  action: rebuild
        volumes:
            - app_node_modules:/app/node_modules

    prisma_studio:
        restart: on-failure:2
        ports:
            - 5557:5555

    database:
        ports:
            - 5436:5432
