services:
    server:
        image: muchimuchi/project-management-system:latest
        restart: unless-stopped
        env_file:
            - .env.production
        command: ["start"]

    database:
        restart: unless-stopped

    prisma_studio:
        restart: unless-stopped
