services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure:5
        environment:
            - PORT=3000
            - BASE_URL=http://localhost
            - NODE_ENV=development
        env_file:
            - ./.env.dev
        ports:
            - 3002:3000
        command: ["--dev"]
        develop:
            watch:
                - path: ./
                  target: /app
                  action: sync
                  ignore:
                      - node_modules/
                      - ./.nginx
                - path: package.json
                  action: rebuild
        volumes:
            - app_node_modules:/app/node_modules

    prisma_studio:
        ports:
            - 5557:5555
        env_file:
            - ./.env.dev

    database:
        ports:
            - 5434:5432
        env_file:
            - ./.env.dev
