services:
    server:
        image: muchimuchi/project-management-system:latest
        restart: unless-stopped
        env_file:
            - .env.production
        command: ["start"]
        ports:
            - 3002:3000

    database:
        restart: unless-stopped

    prisma_studio:
        restart: unless-stopped
        ports:
            - 5557:5555
