services:
    server:
        restart: on-failure:5
        env_file:
            - .env.dev
        ports:
            - 3002:3000
        command: ["run", "dev"]
        develop:
            watch:
                - path: ./
                  target: /app
                  action: sync
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json

    prisma_studio:
        restart: on-failure:2
        ports:
            - 5557:5555

    database:
        ports:
            - 5436:5432

    reverse_proxy:
        restart: on-failure
        ports:
            - 80:80
        develop:
            watch:
                - action: sync+restart
                  path: nginx/default.conf
                  target: /etc/nginx/conf.d/default.conf
