services:
    server:
        container_name: pms_server
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: 3000
            BASE_URL: http://localhost
            SANDBOX_DATABASE_URL: postgresql://prisma:prisma@database:5432/prisma_dev?schema=public
        ports:
            - 3002:3000
        depends_on:
            - database
            # - prisma_studio
        volumes:
            - .:/app
            - app_node_modules:/app/node_modules
    # prisma_studio:
    #     build:
    #         context: /app/src/alt_schema
    #         dockerfile: /app/src/alt_schema/Dockerfile
    #     container_name: prisma_studio
    #     ports:
    #         - 5557:5555
    #     command: npx prisma studio
    #     depends_on:
    #         - database
    #     volumes:
    #         - prisma_studio_vol:/app/src/alt_schema
    database:
        image: postgres:14.3
        container_name: pms_database
        ports:
            - 5436:5432
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: prisma_dev
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
    prisma_studio_vol:
    app_node_modules:
